resources:
  repositories:
  - repository: templates
    type: git
    name: azure-pipeline-templates
    ref: refs/heads/master

trigger:
  branches:
    include: [ master ]

jobs:
- template: job-templates/semver.yml@templates
- job: deploy
  displayName: nuget deploy
  dependsOn:
  - semver
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - template: semver-set-env.yml@templates
  - powershell: |
      $v = "$($env:GITVERSION_SEMVER)"
      "##vso[task.setvariable variable=NUGET_VERSION;]$v"
  - powershell: 'gci env:'
  - task: MarkLindell.h2hextension.envsubst.envsubst@1
    displayName: 'fix versions in files'
    inputs:
      Contents: |
        *.nuspec
        *.psd1
  - task: NuGetCommand@2
    displayName: 'Nuget pack'
    inputs:
      command: pack
      packagesToPack: '*.nuspec'
  - task: NuGetCommand@2
    displayName: 'NuGet push'
    inputs:
      command: push
      publishVstsFeed: 'e34d41e4-409d-4d02-ac17-deb3eea94241'
    condition: (and(succeeded(), eq(variables['GITVERSION_BuildMetaData'], '')))
