resources:
  repositories:
  - repository: templates
    type: git
    name: azure-pipeline-templates
    ref: refs/heads/master

trigger:
  branches:
    include: [ master ]

jobs:
- template: job-templates/semver.yml@templates
- job: deploy
  displayName: nuget deploy
  dependsOn:
  - semver

  steps:

  - template: semver-set-env.yml@templates

  - powershell: |
      $v = "$($env:GITVERSION_SEMVER)-alpha-$($env:GITVERSION_BUILDMETADATA)"
      "##vso[task.setvariable variable=NUGET_VERSION;]$v"
    condition: and(succeeded(), ne(variables['GITVERSION_BuildMetaData'], '0'))
    displayName: set param nuget version (for alpha build)
    
  - powershell: |
      $v = "$($env:GITVERSION_SEMVER)"
      "##vso[task.setvariable variable=NUGET_VERSION;]$v"
    condition: and(succeeded(), eq(variables['GITVERSION_BuildMetaData'], '0'))
    displayName: set param nuget version (for release)    
    
  - task: MarkLindell.h2hextension.envsubst.envsubst@1
    inputs:
      Contents: |
        *.nuspec
        *.psd1
    displayName: 'fix versions in files'

  - task: NuGetCommand@2
    inputs:
      command: pack
      packagesToPack: '*.nuspec'
    displayName: 'Nuget pack'

  - task: NuGetAuthenticate@0
    displayName: 'NuGet Authenticate'
    inputs:
      nuGetServiceConnections: nuget.org
    condition: and(succeeded(), ne(variables['GITVERSION_BuildMetaData'], '0'))

  - task: NuGetCommand@2
    inputs:
      command: push
      publishVstsFeed: 'e34d41e4-409d-4d02-ac17-deb3eea94241'
      nuGetFeedType: external
      publishFeedCredentials: nuget.org
    condition: and(succeeded(), ne(variables['GITVERSION_BuildMetaData'], '0'))
    displayName: 'NuGet push' 
